//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Academics.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Academics extends Mobile User {
	public void display_syllabus() {
	
	}
	
	public void display_result() {
	
	}
	
	public void provide_ebooks() {
	
	}
}
