//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Admin {
	public string admin_id;
	public string admin_pw;
	public void uploads_data_to_web() {
	
	}
}
