//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calender.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Calender extends Mobile User {
	public void sync_calender() {
	
	}
	
	public void notify_events() {
	
	}
	
	public void add_dates() {
	
	}
}
