//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Campus2Campus.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Campus2Campus extends Mobile User {
	public void student_chat() {
	
	}
	
	public void campus_search() {
	
	}
	
	public void gallery() {
	
	}
}
