//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Database.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Database {
	public string database_manager_id;
	public string database_manager_pw;
	public void stores_data() {
	
	}
	
	public void sends_data_to_app() {
	
	}
}
