//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entertainment.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Entertainment extends Mobile User {
	public void find_location_gym() {
	
	}
	
	public void find_location_hangout() {
	
	}
	
	public void find_location_restraunts() {
	
	}
	
	public void find_location_malls() {
	
	}
}
