//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mobile System.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Mobile System {
	public integer location_id;
	public string location;
	public integer time_date;
	public integer imei;
	public void obtain_location() {
	
	}
	
	public void sync_calender() {
	
	}
}
