//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mobile User.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Mobile User {
	public string user_name;
	public string password;
	public num college_id;
	public void read_news() {
	
	}
	
	public void access_academics() {
	
	}
	
	public void access_c2c() {
	
	}
	
	public void access_entertainment() {
	
	}
	
	public void access_calender() {
	
	}
}
