//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : News Feed.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class News Feed extends Mobile User {
	public void display_news() {
	
	}
	
	public void sort_news() {
	
	}
	
	public void update() {
	
	}
}
