//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Web User.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Web User {
	public string user_name;
	public string password;
	public num college_id;
	public void access_academics() {
	
	}
	
	public void access_c2c() {
	
	}
}
