//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Website.java
//  @ Date : 10/14/2016
//  @ Author : 
//
//




public class Website {
	public integer admin_id;
	public string admin_password;
	public num user_id;
	public string user_password;
	public string user_name;
	public void uploads_data_to_db() {
	
	}
	
	public void academics() {
	
	}
	
	public void c2c() {
	
	}
}
